services:
  eink_dashboard_host:
    platform: linux/amd64
    restart: unless-stopped
    image: "eink_dashboard_host"
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    # volumes:
    #   - ./apps/dashboard-host/public:/app/apps/dashboard-host/public:rw
    environment:
      # SEE ./apps/dashboard-host/src/lib/config.ts for many configuration options!
      - PORT=8000
      - SNAP_INTERVAL_S=1800 # 30 minutes
      - NYT_API_KEY=$NYT_API_KEY
# DISPLAY_WIDTH = "820",
# DISPLAY_HEIGHT = "1200",
# SNAP_WRITE_DIRNAME = "./public",
# SNAP_URL_ORIGIN = `http://localhost:${PORT}`,
# SNAP_URL_PATHNAME = "/",
# SNAP_URL_SEARCH = "?kind=airquality",
# SNAP_TZ = process.env.TZ,
# SNAP_IMAGE_BASENAME = "airquality.png",
